export const signIn = {
    REQUEST: 'SIGN_IN_REQUEST',
    SUCCESS: 'SIGN_IN_SUCCESS',
    FAIL: 'SIGN_IN_FAIL'
}

export const signUp = {
    REQUEST: 'SIGN_UP_REQUEST',
    SUCCESS: 'SIGN_UP_SUCCESS',
    FAIL: 'SIGN_UP_FAIL'
}

export const documents = {
    REQUEST: 'DOCUMENT_FETCH_REQUEST',
    SUCCESS: 'DOCUMENT_FETCH_SUCCESS',
    FAIL: 'DOCUMENT_FETCH_FAIL'
}

export const fields = {
    REQUEST: 'FIELDS_FETCH_REQUEST',
    SUCCESS: 'FIELDS_FETCH_SUCCESS',
    FAIL: 'FIELDS_FETCH_FAIL'
}

export const upload = {
    REQUEST: 'UPLOAD_REQUEST',
    SUCCESS: 'UPLOAD_SUCCESS',
    FAIL: 'UPLOAD_FAIL'
}